"""
End-to-end test for examples/zlm-tinychat: build with --target 128k, run on the
simulator with the real tinychat weights paged across banks 0/1/3/4, and assert
that 'HELLO' produces 'HI' as z80ai's documented chatbot output.

This is the moment-of-truth test for the entire D.1 pipeline:
  * tools/zlm_pack.py read model.npz correctly
  * trigram and context encoders match z80ai byte-for-byte
  * linear-cell does dot+bias+arshift correctly
  * 128K bank-switching paged the right weights for each layer
  * autoregressive loop produced the expected chars and stopped at NUL

The simulator run is slow (tens of seconds per call); marked `slow` so devs can
skip it during quick iterations.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from zt.compile.compiler import Compiler
from zt.sim import (
    DEFAULT_DATA_STACK_TOP_128K,
    DEFAULT_RETURN_STACK_TOP_128K,
    SPECTRUM_FONT_BASE,
    TEST_FONT,
    Z80,
    decode_screen_text,
)


EXAMPLE_DIR = Path(__file__).parent.parent
MAIN = EXAMPLE_DIR / "main.fs"
MODEL_FS = EXAMPLE_DIR / "model.fs"


@pytest.fixture(scope="module")
def screen_text() -> str:
    c = Compiler(
        data_stack_top=DEFAULT_DATA_STACK_TOP_128K,
        return_stack_top=DEFAULT_RETURN_STACK_TOP_128K,
    )
    c.include_stdlib()
    c.compile_source(MAIN.read_text(), source=str(MAIN))
    c.compile_main_call()
    image = c.build()

    m = Z80(mode="128k")
    m.load(c.origin, image)
    m.load(SPECTRUM_FONT_BASE, TEST_FONT)
    for bank, data in c.banks().items():
        m.load_bank(bank, data)
    m.pc = c.words["_start"].address
    m.input_buffer = bytearray(b"HELLO\r")
    m.run(max_ticks=50_000_000)

    raw = decode_screen_text(m.mem, cursor_row=23, cursor_col=0)
    return raw.decode("ascii", errors="replace")


class TestSourceLayout:

    def test_main_file_exists(self):
        assert MAIN.is_file(), \
            "examples/zlm-tinychat/main.fs should ship with the example"

    def test_model_fs_exists(self):
        assert MODEL_FS.is_file(), \
            "examples/zlm-tinychat/model.fs should be generated by tools/zlm_pack.py"


class TestWeightsAreInRightBanks:

    @pytest.fixture(scope="class")
    def compiled(self):
        c = Compiler(
            data_stack_top=DEFAULT_DATA_STACK_TOP_128K,
            return_stack_top=DEFAULT_RETURN_STACK_TOP_128K,
        )
        c.include_stdlib()
        c.compile_source(MAIN.read_text(), source=str(MAIN))
        c.compile_main_call()
        c.build()
        return c

    @pytest.mark.parametrize("symbol,bank,expected_size", [
        ("weights1", 0, 16384),
        ("weights2", 1, 12288),
        ("weights3", 3, 6144),
        ("weights4", 4, 1280),
    ])
    def test_weights_landed_in_assigned_bank(self, compiled, symbol, bank, expected_size):
        addr = compiled.words[symbol].data_address
        assert 0xC000 <= addr < 0x10000, \
            f"{symbol} should resolve to a paged-slot address; got {addr:#06x}"
        bank_image = compiled.bank_image(bank)
        assert len(bank_image) >= expected_size, \
            f"bank {bank} should hold at least {expected_size} bytes for {symbol}; got {len(bank_image)}"


class TestRuntimeOutput:

    @pytest.mark.slow
    def test_query_appears_on_first_line(self, screen_text):
        assert "HELLO" in screen_text, \
            f"the hardcoded query 'HELLO' should appear on screen; got:\n{screen_text}"

    @pytest.mark.slow
    def test_response_is_HI(self, screen_text):
        lines = [ln for ln in screen_text.split("\r") if ln.strip()]
        non_query_lines = [ln for ln in lines if "HELLO" not in ln]
        assert non_query_lines, \
            f"after the query line there should be at least one response line; full screen:\n{screen_text}"
        response = non_query_lines[0]
        assert response.strip() == "HI", \
            f"z80ai's tinychat answers 'HELLO' with 'HI'; got response {response!r}; full screen:\n{screen_text}"
