"""
Tier (B) ground-truth generator for examples/zlm-multilayer.

Produces synthetic weights/inputs for a 4-layer MLP with 2-bit signed weights
matching z80ai's quantization scheme (raw bytes 0..3 map to signed -2..+1).
Emits a Forth `weights.fs` that the on-Spectrum forward pass reads, and offers
a Python `forward()` so tests can compute the expected argmax independently.

Run as a script to regenerate `weights.fs` next to this file.
"""
from __future__ import annotations

import random
from pathlib import Path


SEED = 42
ARCHITECTURE = (8, 8, 4, 3)


def generate(seed: int = SEED) -> tuple[list[int], list[list[list[int]]]]:
    rng = random.Random(seed)
    inputs = [rng.randint(-128, 127) for _ in range(ARCHITECTURE[0])]
    layers = [
        [[rng.randint(0, 3) for _ in range(prev)] for _ in range(cur)]
        for prev, cur in zip(ARCHITECTURE, ARCHITECTURE[1:])
    ]
    return inputs, layers


def _signed(raw: int) -> int:
    return raw - 2


def _row_dot(row: list[int], acts: list[int]) -> int:
    return sum(_signed(w) * a for w, a in zip(row, acts))


def forward(inputs: list[int], layers: list[list[list[int]]]) -> list[list[int]]:
    final_idx = len(layers) - 1
    activations: list[int] = list(inputs)
    history: list[list[int]] = [activations]
    for li, weight_matrix in enumerate(layers):
        next_activations = [_row_dot(row, activations) for row in weight_matrix]
        if li < final_idx:
            next_activations = [max(0, z) for z in next_activations]
        activations = next_activations
        history.append(activations)
    return history


def argmax(values: list[int]) -> int:
    return max(range(len(values)), key=lambda i: values[i])


def pack_byte(four_weights: list[int]) -> int:
    w0, w1, w2, w3 = four_weights
    return w0 | (w1 << 2) | (w2 << 4) | (w3 << 6)


def pack_layer(weights: list[list[int]]) -> bytes:
    out = bytearray()
    for row in weights:
        assert len(row) % 4 == 0, "row width must be multiple of 4"
        for i in range(0, len(row), 4):
            out.append(pack_byte(row[i:i + 4]))
    return bytes(out)


def _format_input_block(inputs: list[int]) -> list[str]:
    cells_per_line = 8
    lines = ["create acts0"]
    for i in range(0, len(inputs), cells_per_line):
        chunk = inputs[i:i + cells_per_line]
        lines.append("  " + " ".join(f"{v} ," for v in chunk))
    return lines


def _format_layer_block(index: int, packed: bytes) -> list[str]:
    bytes_per_line = 8
    lines = [f"create weights{index}"]
    for i in range(0, len(packed), bytes_per_line):
        chunk = packed[i:i + bytes_per_line]
        lines.append("  " + " ".join(f"${b:02X} c," for b in chunk))
    return lines


def to_forth_source(inputs: list[int], layers: list[list[list[int]]]) -> str:
    lines = [
        "\\ Generated by examples/zlm-multilayer/gen_weights.py — do not edit.",
        f"\\ seed={SEED} architecture={ARCHITECTURE}",
        "",
    ]
    lines.extend(_format_input_block(inputs))
    lines.append("")
    for i, layer in enumerate(layers, start=1):
        lines.extend(_format_layer_block(i, pack_layer(layer)))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    inputs, layers = generate()
    source = to_forth_source(inputs, layers)
    out_path = Path(__file__).parent / "weights.fs"
    out_path.write_text(source)
    final = forward(inputs, layers)[-1]
    print(f"wrote {out_path}")
    print(f"inputs:        {inputs}")
    print(f"final logits:  {final}")
    print(f"argmax:        {argmax(final)}")


if __name__ == "__main__":
    main()
