\ Generated by examples/zlm-multilayer/gen_weights.py — do not edit.
\ seed=42 architecture=(8, 8, 4, 3)

create acts0
  -71 , -116 , 12 , -3 , -14 , -57 , -76 , -84 ,

create weights1
  $03 c, $45 c, $B7 c, $B4 c, $96 c, $30 c, $2A c, $33 c,
  $1A c, $24 c, $B1 c, $9B c, $26 c, $D5 c, $9B c, $84 c,

create weights2
  $4B c, $F6 c, $67 c, $F9 c, $D6 c, $40 c, $CD c, $2F c,

create weights3
  $28 c, $DE c, $18 c,
