"""
Tier (C) ground-truth generator for examples/zlm-trigram.

Ports z80ai's TrigramEncoder (feedme.py) byte-for-byte: polynomial rolling hash
with multiplier 31 mod 65536, then bucket = h % num_buckets. The Forth port in
main.fs must match this exactly for the on-screen prediction to agree with what
Python computes.

Synthetic weights for a 256 → 32 → 8 → 4 MLP. The 256-input first layer is the
first "real-sized" exercise of `2BIT-DOT+!` per the tier (C) plan. The 4-class
output maps to charset "ABCD".

Context buckets are zero-filled for tier (C); the proper port of ContextEncoder
(which uses position-aware n-gram hashing) is deferred to tier (D) where it
matters for byte-perfect agreement against real model weights.

Run as a script to regenerate weights.fs.
"""
from __future__ import annotations

import random
from pathlib import Path


SEED = 314
NUM_BUCKETS = 128
ARCHITECTURE = (256, 32, 8, 4)
CHARSET = "ABCD"
QUERY_TEXT = "HELLO"


def raw_hash(text: str) -> int:
    h = 0
    for c in text:
        h = (h * 31 + ord(c)) & 0xFFFF
    return h


def hash_trigram(trigram: str, num_buckets: int = NUM_BUCKETS) -> int:
    return raw_hash(trigram) % num_buckets


def encode(text: str, num_buckets: int = NUM_BUCKETS) -> list[int]:
    vec = [0] * num_buckets
    padded = " " + text.lower() + " "
    for i in range(len(padded) - 2):
        bucket = hash_trigram(padded[i:i + 3], num_buckets)
        vec[bucket] += 1
    return vec


def empty_context_buckets(num_buckets: int = NUM_BUCKETS) -> list[int]:
    return [0] * num_buckets


def generate(seed: int = SEED):
    rng = random.Random(seed)
    layers = [
        [[rng.randint(0, 3) for _ in range(prev)] for _ in range(cur)]
        for prev, cur in zip(ARCHITECTURE, ARCHITECTURE[1:])
    ]
    return QUERY_TEXT, empty_context_buckets(), layers


def _signed(raw: int) -> int:
    return raw - 2


def _row_dot(row, acts) -> int:
    return sum(_signed(w) * a for w, a in zip(row, acts))


def forward(input_vector, layers):
    final_idx = len(layers) - 1
    activations = list(input_vector)
    history = [activations]
    for li, weight_matrix in enumerate(layers):
        next_acts = [_row_dot(row, activations) for row in weight_matrix]
        if li < final_idx:
            next_acts = [max(0, z) for z in next_acts]
        activations = next_acts
        history.append(activations)
    return history


def build_input_vector(query: str, context) -> list[int]:
    return encode(query) + list(context)


def _argmax(values):
    return max(range(len(values)), key=lambda i: values[i])


def predict_char_index(query: str, context, layers) -> int:
    inputs = build_input_vector(query, context)
    logits = forward(inputs, layers)[-1]
    return _argmax(logits)


def predict_char(query: str, context, layers) -> str:
    return CHARSET[predict_char_index(query, context, layers)]


def pack_byte(four_weights) -> int:
    w0, w1, w2, w3 = four_weights
    return w0 | (w1 << 2) | (w2 << 4) | (w3 << 6)


def pack_layer(weights) -> bytes:
    out = bytearray()
    for row in weights:
        assert len(row) % 4 == 0, "row width must be multiple of 4"
        for i in range(0, len(row), 4):
            out.append(pack_byte(row[i:i + 4]))
    return bytes(out)


def _format_query_block(query: str) -> list[str]:
    chars = [f"${ord(c):02X} c," for c in query]
    return [
        "create query-text",
        "  " + " ".join(chars),
        f"{len(query)} constant query-len",
    ]


def _format_charset_block() -> list[str]:
    chars = [f"${ord(c):02X} c," for c in CHARSET]
    return [
        "create charset",
        "  " + " ".join(chars),
    ]


def _format_layer_block(index: int, packed: bytes) -> list[str]:
    bytes_per_line = 16
    lines = [f"create weights{index}"]
    for i in range(0, len(packed), bytes_per_line):
        chunk = packed[i:i + bytes_per_line]
        lines.append("  " + " ".join(f"${b:02X} c," for b in chunk))
    return lines


def to_forth_source(query: str, context, layers) -> str:
    lines = [
        "\\ Generated by examples/zlm-trigram/gen_weights.py — do not edit.",
        f"\\ seed={SEED} architecture={ARCHITECTURE} charset={CHARSET!r} query={query!r}",
        "",
    ]
    lines.extend(_format_query_block(query))
    lines.append("")
    lines.extend(_format_charset_block())
    lines.append("")
    for i, layer in enumerate(layers, start=1):
        lines.extend(_format_layer_block(i, pack_layer(layer)))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    query, context, layers = generate()
    src = to_forth_source(query, context, layers)
    out_path = Path(__file__).parent / "weights.fs"
    out_path.write_text(src)
    inputs = build_input_vector(query, context)
    history = forward(inputs, layers)
    char_idx = _argmax(history[-1])
    nonzero = {i: v for i, v in enumerate(encode(query)) if v > 0}
    print(f"wrote {out_path}")
    print(f"query:        {query!r}")
    print(f"buckets nonzero: {nonzero}")
    print(f"final logits: {history[-1]}")
    print(f"argmax:       {char_idx}")
    print(f"char:         {CHARSET[char_idx]!r}")


if __name__ == "__main__":
    main()
