"""
Pack a z80ai model.npz into a Forth source file consumable by zt.

The .npz holds quantized weights (int8 in [-2, +1]) and biases (int16) plus
architecture/charset metadata. We emit a .fs that:

  - declares constants for layer sizes and charset length
  - emits the charset bytes
  - per layer: emits biasN as int16 cells in the main code area, and weightsN
    inside a `BANK in-bank ... end-bank` block at $C000 of the assigned bank

Weight packing: 4 weights per byte, LSB-first, with byte_value = weight + 2
mapping {-2,-1,0,+1} to {0,1,2,3}. This matches z80ai's convention and the
2BIT-DOT+! kernel.

Default bank assignment is one weight matrix per bank: fc1→0, fc2→1, fc3→3,
fc4→4. Banks 2 and 5 are always-mapped under 128K.

Usage:
  uv run python tools/zlm_pack.py --npz model.npz --output model.fs
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


DEFAULT_BANK_ASSIGNMENT = (0, 1, 3, 4)


def pack_weights(int8_matrix: np.ndarray) -> bytes:
    out = bytearray()
    for row in int8_matrix:
        assert row.shape[0] % 4 == 0, f"row width {row.shape[0]} must be multiple of 4"
        for i in range(0, row.shape[0], 4):
            w0 = (int(row[i + 0]) + 2) & 0x3
            w1 = (int(row[i + 1]) + 2) & 0x3
            w2 = (int(row[i + 2]) + 2) & 0x3
            w3 = (int(row[i + 3]) + 2) & 0x3
            out.append(w0 | (w1 << 2) | (w2 << 4) | (w3 << 6))
    return bytes(out)


def _load_layers(npz_path: Path):
    data = np.load(npz_path, allow_pickle=False)
    layers = []
    i = 1
    while f"fc{i}_weight" in data:
        layers.append((data[f"fc{i}_weight"], data[f"fc{i}_bias"]))
        i += 1
    arch = json.loads(bytes(data["_architecture"]).decode())
    charset = bytes(data["_charset"]).decode("latin-1")
    return layers, arch, charset


def _format_byte_block(name: str, payload: bytes, *, bytes_per_line: int = 16) -> list[str]:
    lines = [f"create {name}"]
    for i in range(0, len(payload), bytes_per_line):
        chunk = payload[i:i + bytes_per_line]
        lines.append("  " + " ".join(f"${b:02X} c," for b in chunk))
    return lines


def _format_int16_block(name: str, values) -> list[str]:
    lines = [f"create {name}"]
    per_line = 8
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        lines.append("  " + " ".join(f"{int(v) & 0xFFFF} ," for v in chunk))
    return lines


def _format_charset(charset: str) -> list[str]:
    payload = charset.encode("latin-1")
    return _format_byte_block("charset", payload)


def emit_forth(npz_path: Path, output_path: Path,
               banks: tuple[int, ...] = DEFAULT_BANK_ASSIGNMENT) -> dict:
    layers, arch, charset = _load_layers(npz_path)
    if len(layers) != len(banks):
        raise ValueError(
            f"expected {len(banks)} layers for bank assignment {banks}, got {len(layers)} in npz"
        )

    sizes = [arch["input_size"]] + arch["hidden_sizes"] + [arch["num_classes"]]
    lines = [
        f"\\ Generated by tools/zlm_pack.py from {npz_path.name} -- do not edit.",
        f"\\ architecture: {' -> '.join(str(s) for s in sizes)}",
        f"\\ charset:      {charset!r}",
        "",
    ]
    lines.append(f"{sizes[0]} constant input-size")
    for i, size in enumerate(sizes[1:-1], start=1):
        lines.append(f"{size} constant hidden{i}-size")
    lines.append(f"{sizes[-1]} constant output-size")
    lines.append(f"{len(charset)} constant charset-len")
    lines.append("")
    lines.extend(_format_charset(charset))
    lines.append("")

    metadata = {"layers": [], "charset": charset, "architecture": sizes}
    for li, ((weight, bias), bank) in enumerate(zip(layers, banks), start=1):
        packed = pack_weights(weight)
        lines.extend(_format_int16_block(f"bias{li}", bias.tolist()))
        lines.append("")
        lines.append(f"{bank} constant bank-fc{li}")
        lines.append(f"{bank} in-bank")
        lines.extend(_format_byte_block(f"weights{li}", packed))
        lines.append("end-bank")
        lines.append("")
        metadata["layers"].append({
            "layer": li,
            "out_features": int(weight.shape[0]),
            "in_features": int(weight.shape[1]),
            "packed_bytes": len(packed),
            "bank": bank,
            "bias_bytes": len(bias) * 2,
        })

    output_path.write_text("\n".join(lines).rstrip() + "\n")
    return metadata


def main() -> None:
    parser = argparse.ArgumentParser(description="Pack z80ai model.npz into a zt-includable .fs")
    parser.add_argument("--npz", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--banks", type=int, nargs="+", default=list(DEFAULT_BANK_ASSIGNMENT))
    args = parser.parse_args()
    metadata = emit_forth(args.npz, args.output, banks=tuple(args.banks))
    print(f"wrote {args.output}")
    print(f"architecture: {' -> '.join(str(s) for s in metadata['architecture'])}")
    for lyr in metadata["layers"]:
        print(f"  layer {lyr['layer']}: {lyr['in_features']:>3d} -> {lyr['out_features']:>3d}, "
              f"{lyr['packed_bytes']:>5d} bytes weights in bank {lyr['bank']}, "
              f"{lyr['bias_bytes']} bytes biases")


if __name__ == "__main__":
    main()
